fix(update-bootengine): Fix terrible typo that broke namespace creation.
No idea how I managed to not notice this till today but
update-bootengine has not been automatically creating new filesystem
namespaces for quite some time now. Oops.

diff --git a/update-bootengine b/update-bootengine
--- a/update-bootengine
+++ b/update-bootengine
@@ -66,12 +66,16 @@ mount_private() {
 if [[ "$SETUP_MOUNTS" -eq 1 ]]; then
     # To ensure we don't break the rest of the system re-run ourselves in
     # a new namespace, that way no one else sees our mounts.
-    if cmp -s /proc/self/mountinfo /proc/self/${PPID}/mountinfo; then
+    if cmp -s /proc/self/mountinfo /proc/${PPID}/mountinfo; then
         echo "Creating new filesystem namespace"
         exec unshare --mount -- "$0" "$@"
         exit 1
     fi
 
+    if cmp -s /proc/self/mountinfo /proc/${PPID}/mountinfo; then
+        echo "Creating a new filesystem namespace seems to have failed!" >&2
+        exit 1
+    fi
 
     echo "Mounting virtual filesystems"
     mount_private
